# Generated by Django 5.1.1 on 2024-09-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='round',
            field=models.BooleanField(default=0),
        ),
    ]
