# Generated by Django 5.1.1 on 2024-09-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_game_currnt_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='ty',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='currnt_move',
            field=models.CharField(default='o', max_length=10),
        ),
    ]
